name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  ci:
    uses: KeibaAI-developer/library-workflow/.github/workflows/ci.yml@feat/migrate-to-ruff
    with:
      package_name: discord_logger
      repo_name: discord-logger
